change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
name-template: 'v$NEXT_PATCH_VERSION (DRAFT)'
template: |
  ## Contributors
  $CONTRIBUTORS

  ## Changes
  $CHANGES

  ---
  Previous Tag: `$PREVIOUS_TAG`
