change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Contributers
  $CONTRIBUTORS

  ## Changes
  $CHANGES

  ---
  Previous Tag: `$PREVIOUS_TAG`
